
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wljwflruhhvzlgzjiycf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsandmbHJ1aGh2emxnemppeWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjQ1NjIsImV4cCI6MjA1Nzk0MDU2Mn0.FddjYNO9fiuZmCcxhd-IpB1pmtxnk6t5PpsHPNYMeNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
